// apps/web-nextjs/src/app/error/page.tsx
import type { Error } from "api";

export default function ErrorPage({
  searchParams,
}: {
  searchParams: {
    id: string;
    // TODO: include string while still keeping autocomplete
    cause?: Error;
  };
}) {
  return (
    <main>
      <h1>Error</h1>
      <pre>ID = {searchParams.id}</pre>
      <pre>searchParams = {JSON.stringify(searchParams, null, 2)}</pre>
    </main>
  );
}

// apps/web-solid-start/src/routes/error.tsx
import type { VoidComponent } from "solid-js";
import { useSearchParams } from "solid-start";

import type { Error } from "api";

const ErrorPage: VoidComponent = () => {
  // TODO: include string while still keeping autocomplete
  const [searchParams] = useSearchParams<{ id: string; cause?: Error }>();

  return (
    <main>
      <h1>Error</h1>
      <pre>ID = {searchParams.id}</pre>
      <pre>searchParams = {JSON.stringify(searchParams, null, 2)}</pre>
    </main>
  );
};

export default ErrorPage;
