// apps/web-nextjs/src/app/error/page.tsx
import type { Error } from "api";

export default function ErrorPage({
  searchParams,
}: {
  searchParams: {
    id: string;
    cause?: Error | (string & {});
  };
}) {
  return (
    <main>
      <h1>Error</h1>
      <pre>ID = {searchParams.id}</pre>
      <pre>searchParams = {JSON.stringify(searchParams, null, 2)}</pre>
    </main>
  );
}

// apps/web-svelte-kit/src/routes/error/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';

	let searchParams = $page.url.searchParams;

	const id = searchParams.get('id');
	const cause = searchParams.get('cause');
</script>

<main>
	<h1>Error</h1>
	<pre>ID = {id}</pre>
	<pre>searchParams = {JSON.stringify(Object.fromEntries(searchParams.entries()), null, 2)}</pre>
</main>
