// apps/web-nextjs/src/app/[id]/(redirect)/page.tsx
import { redirect } from "next/navigation";

import { api, errorUrl } from "api";

export default async function RedirectPage({
  params,
}: {
  params: {
    id: string;
  };
}) {
  const res = await api.lengthen(params.id);

  if (res.success) {
    redirect(res.data.url);
  } else {
    redirect(errorUrl(params.id, "NotFound"));
  }
}

// apps/web-solid-start/src/routes/[id]/(redirect).tsx
import type { VoidComponent } from "solid-js";
import { type RouteDataArgs, createRouteData, redirect } from "solid-start";

import { api, errorUrl } from "api";

export function routeData({ params }: RouteDataArgs) {
  return createRouteData(
    async ({ id }) => {
      const res = await api.lengthen(id);

      if (res.success) {
        throw redirect(res.data.url);
      } else {
        throw redirect(errorUrl(id, "NotFound"));
      }
    },
    {
      key: () => ({
        id: params.id,
        key: "redirect",
      }),
    },
  );
}

/**
 * Is not meant to display anything.
 */
const RedirectPage: VoidComponent = () => null;

export default RedirectPage;
