// packages/ui-react/src/loading-spinner.tsx
import type { ComponentProps } from "react";
import { Loader2 } from "lucide-react";

import { cn } from "ui-core";

export interface LoadingSpinnerProps extends ComponentProps<typeof Loader2> {}

export const LoadingSpinner = (props: LoadingSpinnerProps) => {
  return (
    <Loader2
      {...props}
      className={cn("h-4 w-4 animate-spin", props.className)}
    />
  );
};

// packages/ui-svelte/src/loading-spinner/LoadingSpinner.svelte
<script lang="ts">
	import type { ComponentProps } from 'svelte';
	import { Loader2 } from 'lucide-svelte';

	import { cn } from 'ui-core/utils';

	let className: string | undefined | null = undefined;
	export { className as class };

	type $$Props = ComponentProps<Loader2>;
</script>

<Loader2 {...$$restProps} class={cn('h-4 w-4 animate-spin', className)} />
