// apps/web-solid-start/src/components/status-display.tsx
import { type VoidComponent, Match, Switch } from "solid-js";
import { A } from "solid-start";

import type { ActionStatus } from "~/routes/(home)";

export interface StatusDisplayProps extends ActionStatus {}

export const StatusDisplay: VoidComponent<StatusDisplayProps> = (props) => {
  return (
    <Switch>
      <Match when={props.pending}>
        <p>Loading...</p>
      </Match>
      <Match when={props.result} keyed>
        {({ id }) => (
          <p>
            <A href={`/${id}`} class="underline">
              BASE_URL/{id}
            </A>
          </p>
        )}
      </Match>
      <Match when={props.error as unknown} keyed>
        {(error) => <p>Error: ${JSON.stringify(error, null, 2)}</p>}
      </Match>
    </Switch>
  );
};

// apps/web-nextjs/src/app/status-display.tsx
import type { UseMutationResult } from "@tanstack/react-query";

import type { ShortenResponse } from "api";

export type StatusDisplayProps = UseMutationResult<
  ShortenResponse,
  unknown,
  string,
  unknown
>;

export const StatusDisplay = ({
  isLoading,
  isError,
  error,
  isSuccess,
  data,
}: StatusDisplayProps) => {
  return (
    <>
      {isLoading && <p>Loading...</p>}
      {isSuccess && (
        <p>
          <a href={`/${data.id}`} className="underline">
            BASE_URL/{data.id}
          </a>
        </p>
      )}
      {isError && <p>Error: ${JSON.stringify(error, null, 2)}</p>}
    </>
  );
};
