// apps/web-nextjs/src/app/login/who-am-i.tsx
"use client";

import { useQuery } from "@tanstack/react-query";

import { api } from "api";
import { Button, LoadingSpinner } from "ui";

export const WhoAmI = () => {
  const whoAmIQuery = useQuery({
    queryKey: ["whoami"],
    queryFn: async () => {
      const me = await api.whoami();
      console.log("i am:", me);
      return me;
    },
  });

  const handleRefetch = () => {
    void whoAmIQuery.refetch();
  };

  return (
    <>
      <pre>
        me ={" "}
        {whoAmIQuery.isFetching && <LoadingSpinner className="mr-2 inline" />}
        <code>{JSON.stringify(whoAmIQuery.data, null, 2)}</code>
      </pre>

      <Button onClick={handleRefetch} variant="destructive">
        Refetch
      </Button>
    </>
  );
};

// apps/web-solid-start/src/components/who-am-i.tsx
import { type VoidComponent, createResource } from "solid-js";

import { api } from "api";
import { Button, LoadingSpinner } from "ui";

export const WhoAmI: VoidComponent = () => {
  const [whoami, { refetch }] = createResource(async () => {
    const me = await api.whoami();
    console.log("i am:", me);
    return me;
  });

  const handleRefetch = () => {
    void refetch();
  };

  return (
    <>
      <pre>
        me = {whoami.loading && <LoadingSpinner class="mr-2 inline" />}
        <code>{JSON.stringify(whoami(), null, 2)}</code>
      </pre>

      <Button onclick={handleRefetch} variant="destructive">
        Refetch
      </Button>
    </>
  );
};
