// apps/web-svelte-kit/src/routes/login/WhoAmI.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	import { api } from 'api';
	import { Button, LoadingSpinner } from 'ui';

	let me = '';
	let promise: ReturnType<typeof api.whoami> | undefined;

	$: promise?.then((data) => {
		me = data;
	});

	onMount(() => {
		promise = api.whoami();
	});

	function handleRefetch() {
		promise = api.whoami();
	}
</script>

<code>
	me ={' '}
	{#await promise}
		<LoadingSpinner class="mr-2 inline" />
	{/await}
	{JSON.stringify(me, null, 2)}
</code>

<Button on:click={handleRefetch} variant="destructive">Refetch</Button>

// apps/web-solid-start/src/components/who-am-i.tsx
import { type VoidComponent, createResource } from "solid-js";

import { api } from "api";
import { Button, LoadingSpinner } from "ui";

export const WhoAmI: VoidComponent = () => {
  const [whoami, { refetch }] = createResource(async () => {
    const me = await api.whoami();
    console.log("i am:", me);
    return me;
  });

  const handleRefetch = () => {
    void refetch();
  };

  return (
    <>
      <code>
        me = {whoami.loading && <LoadingSpinner class="mr-2 inline" />}
        {JSON.stringify(whoami(), null, 2)}
      </code>

      <Button onclick={handleRefetch} variant="destructive">
        Refetch
      </Button>
    </>
  );
};
